### ISSUE TITLE
Doesn't open and refers you to the logs

### ISSUE THREAD

**Issue by DavidFW1960** [winsomehax/plugin.video.tv-gab#1]
Is this working for you? It won't run on either my OSMC Vero or CCwGTV Kodi. I can grab a log but pretty sure it's reproducible....

**Comment by winsomehax** [comment]
I got it working for me before publishing the repo to GitHub.

The plugin doesn't open, or a video?

It would would help to see the message in the logs.

**Comment by DavidFW1960** [comment]
When I open it it just comes up with an error message. I installed from zip file ok it just won't run. I can get a log tomorrow and post it.

**Comment by winsomehax** [comment]
I just updated the add-on dependencies - which I think may have caused the problem for you. When you install it now it should pull in some other add-ons automatically. They were already installed on mine.

On another subject: Anyone using a pre 19 (Matrix) version of KODI can try altering the line in addon.xml

 from 

        import addon="xbmc.python" version="3.0.0"

to 
        import addon="xbmc.python" version="2.26.0"

and repack it and see if it installs and runs. I don't think it uses anything from Kodi 19 or Python 3... so it may work.

**Comment by DavidFW1960** [comment]
https://paste.osmc.tv/lubirisuvo
That is the log. I'll try reinstalling/updating the repo

**Comment by DavidFW1960** [comment]
You're right - must have been the dependencies. All working now. Thanks.

**Comment by DavidFW1960** [comment]
Just one other thing... it only shows 20 results (one page) and chance of next/previous like for Bitchute?
